"""Generate placement measurements only from the independently validated export."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
path='assets/gusty-gardens/broadleaf-family-v1/roblox/manifest.json'
m=json.loads((ROOT/path).read_text())
validation=json.loads((ROOT/path).with_name('validation.json').read_text())
assert validation['status']=='passed' and validation['total_triangles']==m['total_triangles']
def v(x):return 'V('+', '.join(str(n) for n in x)+')'
lines=['--!strict','-- Generated by tools/generate_gusty_broadleaf_spec.py; root socket is local zero.','local V = Vector3.new','local Spec = {}',
       'Spec.library = "GustyBroadleafTemplates"','Spec.bundle = "GustyBroadleafBundle"','Spec.manifest = "'+path+'"','Spec.siteCount = 35',
       'Spec.envelopeMin = V(-9.8, -0.05, -9.4)','Spec.envelopeMax = V(10.2, 17.98, 9.5)','Spec.parts = {']
for a in m['assets']:lines.append('\t'+a['name']+' = { size = '+v(a['dimensions_studs_xyz'])+', center = '+v(a['center'])+' },')
lines+=['}','Spec.variants = {']
for a in m['variants']:lines.append('\t{ id = "'+a['id']+'", size = '+v(a['size'])+', min = '+v(a['bounds_min'])+', max = '+v(a['bounds_max'])+', parts = { '+', '.join('"'+p+'"' for p in a['parts'])+' } },')
lines+=['}','return Spec','']
(ROOT/'src/server/Map/GustyBroadleafSpec.luau').write_text('\n'.join(lines))
print('GUSTY_SPEC_GENERATED')
