"""Regenerate the runtime spec from the validated Powder Fir export manifest."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
manifest='assets/frostbite-peaks/powder-firs-v1/roblox/manifest.json'
data=json.loads((root/manifest).read_text())
def v(a):return 'V('+', '.join(str(x) for x in a)+')'
lines=['--!strict','-- Generated by tools/generate_powder_spec.py from the export manifest.',
       'local V = Vector3.new','local Spec = {}','Spec.library = "FrostbitePowderTemplates"',
       'Spec.bundle = "PowderFirsBundle"','Spec.manifest = "'+manifest+'"','Spec.parts = {']
for a in data['assets']:
    lines.append('\t'+a['name']+' = { size = '+v(a['dimensions_studs_xyz'])+', center = '+v(a['center'])+' },')
lines+=['}','Spec.variants = {']
for a in data['variants']:
    lines.append('\t{ id = "'+a['id']+'", size = '+v(a['size'])+', root = '+v(a['trunk_base'])+', parts = { '+', '.join('"'+x+'"' for x in a['parts'])+' } },')
lines+=['}','Spec.firs = { FP_Alpine_Fir_Tall = true, FP_Alpine_Fir_Medium = true, FP_Alpine_Fir_Sapling = true }','return Spec','']
(root/'src/server/Map/FrostbitePowderSpec.luau').write_text('\n'.join(lines))
