# -*- coding: utf-8 -*-
"""Write src/shared/Build.luau: which code is running.

The module carries the git short hash, the commit time, whether the working
tree had uncommitted changes when stamped, and the stamp time. It is
gitignored, so it never dirties the tree; the game falls back to "unstamped"
when it is missing. Run it before every sync (the local post-commit hook runs
it after each commit):

    python tools/stamp.py
"""
import io
import os
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "shared", "Build.luau")


def git(*args):
    return subprocess.check_output(["git", "-C", ROOT] + list(args)).decode("utf-8", "replace").strip()


def main():
    try:
        short = git("rev-parse", "--short", "HEAD")
        commit_time = git("log", "-1", "--format=%cI")
        dirty = git("status", "--porcelain", "--untracked-files=no") != ""
    except (subprocess.CalledProcessError, OSError) as err:
        sys.stderr.write("stamp: git unavailable (%s); writing an unstamped module\n" % err)
        short, commit_time, dirty = "unstamped", "", False
    stamped_at = time.strftime("%Y-%m-%d %H:%M")
    body = (
        "--!strict\n"
        "-- GENERATED by tools/stamp.py. Do not edit; gitignored.\n"
        "return {\n"
        '\thash = "%s",\n'
        '\tcommitTime = "%s",\n'
        "\tdirty = %s,\n"
        '\tstampedAt = "%s",\n'
        "}\n" % (short, commit_time, "true" if dirty else "false", stamped_at)
    )
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("stamped %s%s at %s -> %s" % (short, "*" if dirty else "", stamped_at, os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
